name: dotnet package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['3.1']

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK ['3.1']
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '3.1'
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal